name: flutter_survey
description: A package that handles the creation and state of a dynamic questionnaire/data collection survey with conditional questions.
version: 0.1.5
homepage: https://github.com/TheRandonauts/flutter_survey

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  build_runner: ^2.2.0
  diffutil_sliverlist: ^0.5.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
